spring:
  application:
    name: desafio
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate: DEBUG